services:
  - type: web
    name: lominic-api
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: node dist/main.js
    rootDir: apps/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REDIRECT_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  - name: lominic-db
    databaseName: lominic_prod
    user: lominic_user
    plan: free
